[tool.poetry]
name = "15puzzlesolver"
version = "0.1.0"
description = ""
authors = ["isakpulkki <isak@pulkki.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
